[mriduls]
display_name = "Mridul Seth"
url = "https://github.com/mriduls"
lat = 25.20
long = 55.27

[stefanv]
display_name = "Stéfan van der Walt"
url = "https://github.com/stefanv"
lat = 39.3280
long = -120.1833

[jjerphan]
display_name = "Julien Jerphanion"
url = "https://github.com/jjerphan"
lat = 48.847759
long = 2.439497
