[mriduls]
display_name = "Mridul Seth"
url = "https://github.com/mriduls"
lat = 25.20
long = 55.27

[stefanv]
display_name = "Stéfan van der Walt"
url = "https://github.com/stefanv"
lat = 39.3280
long = -120.1833

[jjerphan]
display_name = "Julien Jerphanion"
url = "https://github.com/jjerphan"
lat = 48.847759
long = 2.439497

[rossbar]
display_name = "Ross Barnowski"
url = "https://github.com/rossbar"
lat = 34.138217
long = -118.125516

[dschult]
display_name = "Dan Schult"
url = "https://github.com/dschult"
lat = 42.82
long = -75.22

[seberg]
display_name = "Sebastian Berg"
url = "https://github.com/seberg"
lat = 54.15696416115438
long = 10.413883392149868
